### ISSUE TITLE
build breaks against HEAD (4.1.0) irods - /usr/lib/irods/libirods_client.a moved to /usr/lib/libirods_client.a

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [irods/irods_auth_plugin_gsi#10]
irods_auth_plugin_gsi would not build against DEV-4.1.0 - /usr/lib/irods/libirods_client.a moved to /usr/lib/libirods_client.a

**Comment by trel** [comment]
confirmed - we'll get this changed in the move towards 4.1.0.

**Comment by jasoncoposky** [comment]
reference #15
