### ISSUE TITLE
build.sh creates an RPM where libgsi.so is missing the executable bit

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [irods/irods_auth_plugin_gsi#11]
build.sh creates an RPM where libgsi.so is missing the executable bit - causing the plugin to fail loading.

**Comment by trel** [comment]
This appears to be true, but not for .deb based systems...

Since we are using EPM, we should probably default to 755 everywhere.  The verdict here (http://unix.stackexchange.com/a/61650) is that doing so is 'Mostly Harmless'.
