### ISSUE TITLE
Build error on Centos7 iCommands host

### ISSUE THREAD

**Issue by bnordgren** [irods/irods_auth_plugin_gsi#21]
The RPM generated via a build on my iCat server refuses to install on a plain Centos 7 server with icommands installed (requires "irods" package ??!?) So I attempt to build on the client machine. Client machine has: 

    [root@gridftp-test irods_auth_plugin_gsi]# rpm -qa | grep irods
    irods-auth-plugin-krb-1.3-0.x86_64
    irods-dev-4.1.9-0.x86_64
    irods-runtime-4.1.9-0.x86_64
    irods-icommands-4.1.9-0.x86_64

    [root@gridftp-test irods_auth_plugin_gsi]# rpm -qa | grep globus
    globus-gsi-openssl-error-3.7-1.el7+gt6.x86_64
    globus-callout-3.15-3.el7+gt6.x86_64
    globus-gsi-cert-utils-9.15-1.el7+gt6.x86_64
    globus-gssapi-gsi-12.11-1.el7+gt6.x86_64
    globus-io-11.8-1.el7+gt6.x86_64
    globus-proxy-utils-6.18-1.el7+gt6.x86_64
    globus-gass-copy-9.23-1.el7+gt6.x86_64
    globus-authz-callout-error-3.6-3.el7+gt6.x86_64
    globus-gridftp-server-progs-11.8-1.el7+gt6.x86_64
    globus-xio-5.13-4.el7+gt6.x86_64
    globus-common-progs-16.8-2.el7+gt6.x86_64
    globus-usage-4.5-3.el7+gt6.x86_64
    globus-gsi-proxy-ssl-5.10-1.el7+gt6.x86_64
    globus-gsi-sysconfig-6.11-1.el7+gt6.x86_64
    globus-gsi-callback-5.12-1.el7+gt6.x86_64
    globus-gsi-proxy-core-8.6-1.el7+gt6.x86_64
    globus-gss-assist-10.20-1.el7+gt6.x86_64
    globus-xio-gsi-driver-3.10-3.el7+gt6.x86_64
    globus-ftp-control-7.7-2.el7+gt6.x86_64
    globus-gss-assist-progs-10.20-1.el7+gt6.x86_64
    globus-gsi-cert-utils-progs-9.15-1.el7+gt6.x86_64
    globus-ftp-client-8.33-1.el7+gt6.x86_64
    globus-gass-copy-progs-9.23-1.el7+gt6.x86_64
    globus-gridftp-server-control-4.2-4.el7+gt6.x86_64
    globus-authz-3.15-1.el7+gt6.x86_64
    globus-gridftp-server-11.8-1.el7+gt6.x86_64
    globus-gridftp-6.0-1.el7+gt6.x86_64
    globus-toolkit-repo-6-23.noarch
    globus-common-16.8-2.el7+gt6.x86_64
    globus-gfork-4.9-4.el7+gt6.x86_64
    globus-openssl-module-4.8-1.el7+gt6.x86_64
    globus-gsi-credential-7.11-1.el7+gt6.x86_64
    globus-gssapi-error-5.5-3.el7+gt6.x86_64
    globus-gass-transfer-8.10-3.el7+gt6.x86_64
    globus-xio-popen-driver-3.6-3.el7+gt6.x86_64
    globus-xio-pipe-driver-3.9-3.el7+gt6.x86_64
    globus-xio-udt-driver-1.25-1.el7+gt6.x86_64

The build fails complaining that many of the libraries in the above are not found: 

    g++ -DRODS_SERVER  -I/usr/include/irods -I/usr/include/irods/boost  -fPIC "-Wl,-E" -shared -o .././libgsi.so  .objs/libgsi.o -lglobus_gss_assist -lglobus_gssapi_gsi -lglobus_gsi_credential -lglobus_gsi_proxy_core -lglobus_gsi_callback -lglobus_oldgaa -lglobus_gsi_sysconfig -lglobus_gsi_cert_utils -lglobus_openssl_error -lglobus_openssl -lglobus_proxy_ssl -lssl -lcrypto -lglobus_common -lglobus_callout -lltdl /usr/lib/libirods_client_api_table.a /usr/lib/libirods_client_plugins.a
    /usr/bin/ld: cannot find -lglobus_gss_assist
    /usr/bin/ld: cannot find -lglobus_gssapi_gsi
    /usr/bin/ld: cannot find -lglobus_gsi_credential
    /usr/bin/ld: cannot find -lglobus_gsi_proxy_core
    /usr/bin/ld: cannot find -lglobus_gsi_callback
    /usr/bin/ld: cannot find -lglobus_oldgaa
    /usr/bin/ld: cannot find -lglobus_gsi_sysconfig
    /usr/bin/ld: cannot find -lglobus_gsi_cert_utils
    /usr/bin/ld: cannot find -lglobus_openssl_error
    /usr/bin/ld: cannot find -lglobus_openssl
    /usr/bin/ld: cannot find -lglobus_proxy_ssl
    /usr/bin/ld: cannot find -lglobus_common
    /usr/bin/ld: cannot find -lglobus_callout
    /usr/bin/ld: cannot find -lltdl
    collect2: error: ld returned 1 exit status 
    make[1]: *** [.././libgsi.so] Error 1
    make[1]: Leaving directory `/root/irods_auth_plugin_gsi/gsi'
    make: *** [gsi] Error 2

ldconfig -v lists every single one of these libraries. Also, while compiling this code on the iCat server went without a hitch, this has failed on two brand new Centos 7 VMs.

How does one install the GSI authentication plugin into the clients on a machine having only the iCommands?

**Comment by bnordgren** [comment]
I worked around this by forcing the GSI RPM to install in spite of the missing dependency. AFAIKT it's working. However, if "irods" isn't a dependency, it shouldn't be listed as one, or the iCommands package should provide it too. yum will forever complain about a broken RPM database now.

    [root@gridftp-test ~]# rpm -Uvh irods-auth-plugin-gsi-1.3-centos6.rpm --force --nodeps
    Preparing...                          ################################# [100%]
    Updating / installing...
       1:irods-auth-plugin-gsi-1.3-0      ################################# [100%]
    warning: %post(irods-auth-plugin-gsi-1.3-0.x86_64) scriptlet failed, exit status 1

**Comment by trel** [comment]
I see now - [this line is to blame](https://github.com/irods/irods_auth_plugin_gsi/blob/f0eeac5bfb06c5a55a50af273381d0b704900d22/packaging/irods_auth_plugin_gsi.list.template#L12)...

**Comment by trel** [comment]
@bnordgren Please confirm this is sufficient.  Thanks.

**Comment by bnordgren** [comment]
Yum at least tried to install it, but this time failed the irods version check (requires 4.1.10).

    Downloading packages:
    Running transaction check
    Running transaction test
    Transaction test succeeded
    Running transaction
    Local iRODS is 4.1.9
    This plugin requires iRODS 4.1.10
    error: %pre(irods-auth-plugin-gsi-1.4-0.x86_64) scriptlet failed, exit status 1
    Error in PREIN scriptlet in rpm package irods-auth-plugin-gsi-1.4-0.x86_64
      Verifying  : irods-auth-plugin-gsi-1.4-0.x86_64                           1/1

    Failed:
      irods-auth-plugin-gsi.x86_64 0:1.4-0


I downgraded the version number in the [template file](https://github.com/irods/irods_auth_plugin_gsi/blob/master/packaging/irods_auth_plugin_gsi.list.template#L38). yum still has a failure, but at least it installed.

    Downloading packages:
    Running transaction check
    Running transaction test
    Transaction test succeeded
    Running transaction
      Installing : irods-auth-plugin-gsi-1.4-0.x86_64                           1/1
    warning: %post(irods-auth-plugin-gsi-1.4-0.x86_64) scriptlet failed, exit status 1
    Non-fatal POSTIN scriptlet failure in rpm package irods-auth-plugin-gsi-1.4-0.x86_64
      Verifying  : irods-auth-plugin-gsi-1.4-0.x86_64                           1/1

    Installed:
      irods-auth-plugin-gsi.x86_64 0:1.4-0

    Complete!

And it seems to work now.

    [centos@vault ~]$ ils
    /usfs/home/bnordgren:
      dork
      foo

So it appears we're on the right track, but there's a little more tweaking to be done.

**Comment by trel** [comment]
Okay... so the post-scriptlet assumed this was being installed on the server and is trying to update the ownership of the installed files to that of the iRODS server's service account.  

I've added a check to make sure the GSI package is being installed on the server.

I've confirmed this works for me on a new clean machine.

Please try again.

**Comment by bnordgren** [comment]
Seems to work for me.

**Comment by trel** [comment]
Excellent.  Thank you!
