### ISSUE TITLE
credentials for "irods"are used instead of host and user

### ISSUE THREAD

**Issue by sferry** [irods/irods_auth_plugin_gsi#23]
Hello,
I am using the rpm based plugin from there: https://packages.irods.org/yum/pool/centos7/
I don't know who's compiling it, I suppose it is from these src. 

Though I have on the server :
/etc/grid-security/
host(cert)key.pem
certificates/
grid-mapfile
irods/irodscert(key).pem
On the client 
/home/user/.globus/usercert(key).pem
a valid proxy
and the librairies on both client and serveur
/usr/lib/irods/plugins/auth/libgsi_client.so
/usr/lib/irods/plugins/auth/libgsi_server.so

I cannot connect. I get :
<<
remote addresses: xx.xx.xxx.xxx ERROR: unpackNonpointerItem: strlen of msg > dim size, content: DEBUG: On iRODS-Server side: GSS-API error acquiring credentials: GSS Minor Status Error Chain:
globus_gsi_gssapi: Error with GSI credential
globus_gsi_gssapi: Error with gss credential handle
globus_credential: Valid credentials could not be found in any of the possible locations specified by the credential search order.
Valid credentials could not be found in any of the possible locations specified by the credential search order.
Attempt 1
globus_credential: Error reading host credential
globus_sysconfig: Error with certificate filename
globus_sysconfig: Error with certificate filename
globus_sysconfig: File is not owned by current user: /etc/grid-security/hostcert.pem is not owned by current user
Attempt 2
globus_credential: Error reading proxy credential
globus_sysconfig: Could not find a valid proxy certificate file location
globus_sysconfig: Error with key filename
globus_sysconfig: File does not exist: /tmp/x509up_u394 is not a valid file
Attempt 3
globus_credential: Error reading user credential
glob 
remote addresses: xxx.xx.xx.xx ERROR: readAndProcApiReply:unpackStruct error. status = -308000 status = -308000 USER_PACKSTRUCT_INPUT_ERR
[-]     /tmp/tmpqMgH4t/gsi/libgsi.cpp:1175:irods::error gsi_auth_client_request(irods::plugin_context &, rcComm_t *) :  status [GSI_ERROR_ACQUIRING_CREDS]  errno [] -- message [call to rcAuthPluginRequest failed.]
>>

1) the proxy is _UUID of irods user, NOT the user's UID ?!
2) /etc/grid-security/hostcert.pem is own by root, and it seems it want it to be owned by irods (which exists in /etc/grid-security/irods/irodscert(key).pem 

Have you tryed to install & test this ?
Do you have any idea ?
Thanks for anyhelp. 

Sophie

**Comment by sferry** [comment]
I have manage to find what was wrong :
the X509_USER_CERT and X509_USER_KEY is necessary to be set for the service EVEN IF hte default path is used (ie /etc/grid-security/service/servicekey(cert).pem.

**Comment by trel** [comment]
Good find.  Sorry about that.   I'll update the documentation.
