### ISSUE TITLE
restore missing proxy user functionality from legacy

### ISSUE THREAD

**Issue by trel** [irods/irods_auth_plugin_gsi#8]
From @vladimir-mencl-eresearch at https://groups.google.com/forum/#!topic/irod-chat/dOchfGA3ogY

> However, it appears to me the proxy authentication code has plain disappeared from the 4.x libgsi.cpp.
> 
> I can't see it in the source code.
> 
> And I've just set up a test instance where I've:
> 
> * associated my DN with the rods account
> * confirmed I can authenticate to rods via GSI
> * tried to use the rods GSI authentication to work under my account "vlad" with:
> 
> ```
> $clientUserName=vlad ils /BeSTGRID-I4-DEV/home/rods
> ```
> 
> But I got:
> ```
> ERROR: [-]      iRODS/lib/core/src/procApiRequest.cpp:265:readAndProcApiReply :  status [SYS_HEADER_READ_LEN_ERR]  errno [Connection reset by peer] -- message []
>         [-]     iRODS/lib/core/src/sockComm.cpp:195:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [Connection reset by peer] -- message [failed to call 'read header']
>                 [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [Connection reset by peer] -- message [read 0 expected 4]
> 
> [-]     libgsi.cpp:1243:gsi_auth_client_response :  status [SYS_HEADER_READ_LEN_ERR]  errno [Connection reset by peer] -- message [Call to rcAuthResponseFailed.]
> 
>  failed with error -4104 SYS_HEADER_READ_LEN_ERR Connection reset by peer
> Client Caught broken pipe signal. Connection to server may be down
> ERROR: [-]      iRODS/lib/core/src/rcConnect.cpp:257:rcDisconnect :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
>         [-]     iRODS/lib/core/src/sockComm.cpp:1332:sendRodsMsg :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [failed to call 'write body']
>                 [-]     libtcp.cpp:420:tcp_send_rods_msg :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [writeMsgHeader failed]
>                         [-]     iRODS/lib/core/src/sockComm.cpp:454:writeMsgHeader :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message []
>                                 [-]     libtcp.cpp:341:tcp_write_msg_header :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected -1946157056]
> ```
> 
> and rodsLog says:
> 
> ```
> Mar 27 16:08:10 pid:10243 NOTICE: Agent process 10288 exited with status 256
> Mar 27 16:08:10 pid:10243 NOTICE: Agent process 10409 started for puser=rods and cuser=vlad from 132.181.39.31
> Mar 27 16:08:10 pid:10409 NOTICE: igsiServersideAuth: DN mismatch, user=vlad, Certificate DN=/C=TW/O=AP/OU=GRID/CN=Vladimir Mencl 104211, status=-808000
> Mar 27 16:08:10 pid:10409 ERROR: [-]    iRODS/server/core/src/rodsAgent.cpp:335:agentMain :  status [GSI_DN_DOES_NOT_MATCH_USER]  errno [] -- message [Failed during auth plugin agent start for scheme: "gsi".]
>         [-]     libgsi.cpp:986:gsi_auth_agent_start :  status [GSI_DN_DOES_NOT_MATCH_USER]  errno [] -- message [DN mismatch, user=vlad, Certificate DN+/C=TW/O=AP/OU=GRID/CN=Vladimir Mencl 104211, status = -808000.]
> 
> Mar 27 16:08:10 pid:10409 NOTICE: Agent exiting with status = -939000
> ```
> 
> Which really makes it look like the proxy authentication code introduced in 3.3 is gone.
>

**Comment by vladimir-mencl-eresearch** [comment]
Hi, I think this one can be closed now that #9 has been merged (sorry, forgot to include auto-close keyword in the commit message).

Cheers,
Vlad

**Comment by trel** [comment]
agreed - thanks.
